<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Motivation Letter for Embassy</title>
    <style>
        body {
            font-family: 'DejaVu Sans', 'Helvetica', 'Arial', sans-serif;
            line-height: 1.6;
            font-size: 11pt;
            margin: 0;
            padding: 0;
            color: #1f2d3d;
        }
        .letter {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            text-align: lift;
            margin-bottom: 30px;
        }
        .date {
            text-align: right;
            margin-bottom: 20px;
        }
        .subject {
            font-weight: bold;
            margin: 20px 0 10px;
        }
        .signature {
            margin-top: 40px;
        }
        .footer-note {
            font-size: 9pt;
            color: #5a6e7c;
            margin-top: 30px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="letter">
    <div class="header">
        <strong>{{ $full_name }}</strong><br>
        @if($email) Email: {{ $email }}<br>@endif
        @if($phone) Phone: {{ $phone }}<br>@endif
        Age: {{ $age }}
    </div>

    <div class="date">
        Date: {{ $date }}
    </div>

    <div style="margin-bottom: 15px;">
        To: Embassy of <strong>{{ $country }}</strong><br>
        Visa Section<br>
        Dear Honorable Consul,
    </div>

    <div class="subject">
        Subject: Student Visa Application – {{ $scholarship_name }} Scholarship
    </div>

    <p>
        I, the undersigned <strong>{{ $full_name }}</strong>, respectfully submit my application for a student visa to pursue my higher education at <strong>{{ $university }}</strong> under the <strong>{{ $scholarship_name }}</strong> scholarship program in the field of <strong>{{ $specialization }}</strong>.
    </p>

    <p>
        This scholarship is a life-changing opportunity that perfectly aligns with my academic aspirations. I specifically chose <strong>{{ $country }}</strong> because of its outstanding educational reputation, and <strong>{{ $university }}</strong> is renowned worldwide for its excellence in my chosen field.
    </p>

    <p>
        Upon completion of my studies, I have every intention to return to my home country and contribute to its development. I have strong family and professional ties back home, which guarantee my return after finishing the program.
    </p>

    <p>
        The scholarship fully covers tuition fees and living expenses, confirming my financial ability to stay legally and avoid any unauthorized work. I will strictly abide by the visa regulations and leave the country upon completion of my degree.
    </p>

    <p>
        Attached are all required supporting documents (scholarship letter, university admission, academic transcripts, etc.). I kindly request your approval and issuance of the student visa.
    </p>

    <div class="signature">
        Yours faithfully,<br>
        {{ $full_name }}<br>
        Signature: ...................
    </div>

    <div class="footer-note">
        This letter was generated by the Scholarship Platform – a professional template for embassy applications.
    </div>
</div>
</body>
</html>